version: '3.1'

services:
  #Kafka related
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    networks:
      default:
        aliases:
          - zookeeper
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    hostname: kafka
    image: docker.io/bitnami/kafka:3.2
    networks:
      default:
        aliases:
          - kafka
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  my-db:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local